### PR TITLE
openssl 1.1 support

### PR DESCRIPTION
**Pull request by tanner0101**
Overview changes to support OpenSSL 1.1
- New methods added in OpenSSL 1.1 are exposed to 1.0 via shim. 
- All `UnsafePointer`s have been converted to `OpaquePointer` in conformance with OpenSSL 1.1 changes.
- Anytime a pointer is passed to OpenSSL, `.convert()` is called first. This allows Swift to dynamically convert between `UnsafePointer` and `OpaquePointer` where needed.
- `CCryptoOpenSSL` library has been added so that Crypto no longer relies on private NIO modules.

Other changes:
- C libraries have been renamed to follow Swift guidelines. `libbcrypt` -> `CBcrypt`. 
- Tests have been moved from AES128 to AES256CBC (removes annoying warnings).
- Some contributor docs and helpful docker files have been added.

### CODE REVIEW

**Comment by tanner0101** [comment]
Almost working, just one bug left. For some reason a C function stub for OpenSSL < 1.1 is causing a compiler crash. 

stub:
```c
int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d) {
    r->n = n;
    r->e = e;
    r->d = d;
    return 0;
}
```

use site
```swift
        let type: RSAKeyType
        if let d = d {
            type = .private
            RSA_set0_key(rsa, parseBignum(n).convert(), parseBignum(e).convert(), parseBignum(d).convert())
        } else {
            type = .public
            RSA_set0_key(rsa, parseBignum(n).convert(), parseBignum(e).convert(), nil)
        }
```

error:
```
/root/project/.build/checkouts/swift-nio-ssl.git--5891929103443980028/Sources/NIOOpenSSL/OpenSSLHandler.swift:270:35: warning: 'changeCapacity(to:)' is deprecated: changeCapacity has been replaced by reserveCapacity
                    receiveBuffer.changeCapacity(to: receiveBuffer.capacity + 1024)
                                  ^
Compile Swift Module 'Crypto' (15 sources)
swift: /home/buildnode/jenkins/workspace/oss-swift-4.2-package-linux-ubuntu-16_04/llvm/tools/clang/lib/CodeGen/CGRecordLayout.h:187: unsigned int clang::CodeGen::CGRecordLayout::getLLVMFieldNo(const clang::FieldDecl *) const: Assertion `FieldInfo.count(FD) && "Invalid field for record!"' failed.
/usr/bin/swift[0x4108b64]
/usr/bin/swift[0x41069f2]
/usr/bin/swift[0x4108d12]
...
1.	While emitting IR SIL function "@$S6Crypto6RSAKeyV10components1n1e1dACSS_S2SSgtKFZ".
 for 'components(n:e:d:)' at /root/project/Sources/Crypto/RSA/RSAKey.swift:67:12
2.	/root/project/Sources/CCryptoOpenSSL/include/c_crypto_openssl.h:27:5: Generating code for declaration 'RSA_set0_key'
<unknown>:0: error: unable to execute command: Aborted
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /root/project/.build/debug.yaml main output:
```

**Comment by weissi** [comment]
@tanner0101 mind filing that at bugs.swift.org ? Just give them the hash you used or a zip file with the code and the swift build invocation.

**Comment by tanner0101** [comment]
@weissi done: https://bugs.swift.org/browse/SR-8846.

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 896 coins.

**Pull request merged**
