### PR TITLE
Crash fix

### PR DESCRIPTION
**Pull request by rafiki270**
The queen of the lake thinks this will fix a crash I am getting fairly regularly. Please do not ask me why ... :D ... this stuff is above my brains pay grade ...

### CODE REVIEW

**Comment by pedantix** [comment]
as a lowly Knight(tree) of the Queen of the lakes realm, I can back this up. 

https://developer.apple.com/documentation/foundation/data/1780450-withunsafebytes

It is very clear that we cannot rely on this pointer outside of the lifecycle of the closure. I feel  like I need to go check some of my code after learning this

**Comment by rafiki270** [comment]
@pedantix still got a crash on this :(

**Comment by tanner0101** [comment]
Does this fix the issue @rafiki270? I would be surprised if so. I thought that the pointer would stay alive for as long as the parent is alive (which it is for the duration of this closure).

**Comment by rafiki270** [comment]
@tanner0101 nope, I won't be closing this PR for now as I am still trying to find a fix. My app is now crashing about every 5 mins on this :(

**Comment by tanner0101** [comment]
@rafiki270 if you could provide a failing test case that would be very helpful in getting this fixed.

**Pull request closed without merging**
