### PR TITLE
eliminate warnings for Swift 4.1

### PR DESCRIPTION
**Pull request by rpinz**

### CODE REVIEW

**Comment by 0xTim** [comment]
@rpinz I'm assuming this is to silence warnings in Vapor 2? This will need to go into a Vapor 2 branch created from the previous major release since `master` is for Vapor 3 which is 4.1 only

**Comment by grundoon** [comment]
@rpinz I'll go ahead and create a `vapor-2` branch here in `crypto` for this (as well as ones in `core` and `console` for your other remaining conflicting PRs).

**Comment by rpinz** [comment]
Updated pull request branch to vapor-2.

**Comment by penny-coin** [comment]
Hey @rpinz, you just merged a pull request, have a coin! 

You now have 2 coins.

**Pull request merged**
