### PR TITLE
Add several more default cipher algorithms and make initialization with an EVP_CIPHER public

### PR DESCRIPTION
**Pull request by MrMage**
See #59 for discussion. I have not deprecated any of the existing ciphers without further discussion. Note that the new ciphers are unsafe to use without a 128-bit initialization vector.

Regarding making `init(c: UnsafePointer<EVP_CIPHER>)` public: I had issues using `Cipher(named: "aes-256-cfb")` on Linux — the cipher was not found. Using EVP_aes_256_cfb128() worked, however. If this is the case for other ciphers as well, it makes sense to let users pass in any `EVP_CIPHER` they'd like instead of having to refer to them by name.

### CODE REVIEW

**Comment by MrMage** [comment]
I'm starting to get the suspicion that AES-CFB is not supported on my Linux base image (Ubuntu 14.04). However, it might be supported (and desired) on other systems, and AES-CBC works even on my system.

**Comment by tanner0101** [comment]
I don't have a problem with `init(c: UnsafePointer<EVP_CIPHER>)` being made public. It's not really worth keeping the fact that this implementation is based on OpenSSL a secret. If we were to ever switch away from OpenSSL, it would be a breaking change anyway.

**Comment by tanner0101** [comment]
@MrMage would you want to add the deprecations for the old ECB code to this PR?

**Comment by MrMage** [comment]
I have added deprecations, comments, and global constants. Please take another look.

**Comment by MrMage** [comment]
Friendly ping :-)

**Comment by penny-coin** [comment]
Hey @MrMage, you just merged a pull request, have a coin! 

You now have 7 coins.

**Pull request merged**
